planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
start_state_max_bounds_error: 0.1

planner_configs:
  RRTConnect:
    type: geometric::RRTConnect

sekirei_arm:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
  projection_evaluator: joints(arm_joint1,arm_joint2)
  longest_valid_segment_fraction: 0.005
